In [1]:
# Importing header files
import numpy as np
import warnings

warnings.filterwarnings('ignore')


In [2]:
#New record
new_record=[[50,  9,  4,  1,  0,  0, 40, 0 ]]
path = "/Users/rahulkosamkar/Documents/Data_Science/Projects/Numpy Project (make sense of census)/file.csv"

In [3]:
#Reading file
data = np.genfromtxt(path, delimiter=",", skip_header=1)
print("\nData: \n\n", data)
print(data.shape)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]
(1000, 8)


In [4]:
#Code starts here
census = np.concatenate((data,new_record),axis=0)
print(census)
print(census.shape)
age = census [:,0]
max_age = age.max()
print(max_age)
min_age = age.min()
print(min_age)
age_mean = age.mean()
print(age_mean)
age_std = age.std()
print(age_std)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]
(1001, 8)
90.0
17.0
38.06293706293706
13.341478176165857


In [5]:
race_0 = census[census[:,2]==0]
race_1 = census[census[:,2]==1]
race_2 = census[census[:,2]==2]
race_3 = census[census[:,2]==3]
race_4 = census[census[:,2]==4]
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)
length = [len_0,len_1,len_2,len_3,len_4]
print(length)
minority_race = length.index(min(length))
print(minority_race)

[10, 27, 110, 6, 848]
3


In [6]:
senior_citizens = census[census[:,0]>60]
working_hours_sum = senior_citizens.sum(axis=0)[6]
print(working_hours_sum)
senior_citizens_len=len(senior_citizens)
avg_working_hours=working_hours_sum/senior_citizens_len
print((avg_working_hours))

1917.0
31.42622950819672


In [7]:
high=census[census[:,1]>10]
avg_pay_high=high[:,7].mean()
print(avg_pay_high)
low=census[census[:,1]<=10]
avg_pay_low=low[:,7].mean()
print(avg_pay_low)


0.42813455657492355
0.13649851632047477
